name: Build APK from ZIP

on:
  push:
    branches: [ "main" ]    # พุชครั้งต่อไปจะรันอัตโนมัติ
  workflow_dispatch:         # กด Run จากแท็บ Actions ได้ด้วย

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # ป้องกันอาการบรรทัด CRLF ทำให้ gradlew/สคริปต์เพี้ยน
    - name: Git config (no CRLF)
      run: git config --global core.autocrlf false

    # แตกไฟล์ project.zip ที่อยู่รูทของ repo
    - name: Unzip Android project
      run: |
        rm -rf project && mkdir project
        unzip -q project.zip -d project
        # ถ้า zip มีโฟลเดอร์หุ้มอยู่อีกชั้น ให้ย้ายขึ้นมา
        shopt -s nullglob
        roots=(project/*)
        if [ ${#roots[@]} -eq 1 ] && [ -d "${roots[0]}" ]; then
          mv project/*/* project/ 2>/dev/null || true
        fi

    - name: Show found gradle files (debug)
      run: |
        ls -la project
        find project -maxdepth 2 -name "settings.gradle*" -o -name "build.gradle*"

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    - name: Accept SDK licenses
      run: yes | sdkmanager --licenses

    # ซ่อม/สร้าง Gradle Wrapper ถ้าขาดไฟล์ หรือไม่ได้ zip มาด้วย
    - name: Generate/repair Gradle wrapper
      working-directory: project
      run: |
        chmod +x gradlew 2>/dev/null || true
        if [ ! -f gradlew ]; then
          echo "gradlew not found -> generate wrapper with Gradle 8.9"
          curl -sLo gradle.zip https://services.gradle.org/distributions/gradle-8.9-bin.zip
          unzip -q gradle.zip
          gradle-8.9/bin/gradle wrapper
        fi
        # เผื่อกรณี jar ของ wrapper ไม่ถูกใส่มา
        if [ ! -f gradle/wrapper/gradle-wrapper.jar ]; then
          echo "Create wrapper jar with local Gradle"
          ./gradlew wrapper
        fi
        chmod +x gradlew
        # บังคับให้ใช้ Gradle 8.9 (เสถียรกับ Android Gradle Plugin รุ่นใหม่)
        sed -i 's#distributionUrl=.*#distributionUrl=https\\://services.gradle.org/distributions/gradle-8.9-bin.zip#g' gradle/wrapper/gradle-wrapper.properties

    - name: Build Debug APK
      working-directory: project
      run: ./gradlew --warning-mode=all --stacktrace :app:assembleDebug

    # อัปโหลด APK เป็น Artifacts ให้กดโหลด
    - name: Upload APK(s)
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: |
          project/app/build/outputs/apk/debug/*.apk
          project/**/outputs/apk/**/*.apk
